KaufmannDigital:
  GDPR:
    CookieConsent:
      siteCSSFilepath: null
      customCSSFilepath: null
      consentLogEnabled: false
      consentDimensions: []
      # See README.md
      #        - language
      #        - country
      cookieName: 'KD_GDPR_CC'
      cookieDomainName: null
      siteStyles: []
      #        "rootNode name 1":
      #          siteCSSFilepath: <link to css>
      #          customCSSFilepath: <link to custom css>
      #        "rootNode name 2":
      #          siteCSSFilepath: <link to css>
      #          customCSSFilepath: <link to custom css>
      backend:
        includeGeneratedJs: true
      excludeDocumentNodeTypes: []
      # See README.md
      # - 'Vendor.Package:Document.Imprint'
